### ISSUE TITLE
Posting Large number of files in s3 seem to get blueshift acting strange and ignoring large manifest file

### ISSUE THREAD

**Issue by ryanmedlin** [uswitch/blueshift#10]
we have a continuous stream of events coming into our API and placing small amounts of files in the s3 bucket and they are being processed fine.

Sometimes we import form customers very large amount of smaller files and when we do this we see a large manifest file being created and places at the root location..  but as the continous stream of events keep coming we notice that the initial COPY ANALYZE gets aborted and then it just starts importing the small files in a separate manifest and sortof "forgets" about the large one.  Only when i restart blueshift does it reread the folder and create a new manifest and kick of the proper COPY.

is blueshift somehow aborting the large copy when it processes another smaller manifest and then forgets about it?  

I am going to dig into the code a little myself and see if I can follow whats going on there.

Sometimes after restarting it will run the COPY then it aborts:

https://www.dropbox.com/s/a1qdmnc6dsnyjfk/Screenshot%202015-02-03%2012.14.06.png?dl=0

**Comment by ryanmedlin** [comment]
im setting poll interval to a higher number just to make sure thats not getting in its way

**Comment by ryanmedlin** [comment]
amazon thinks its trying to load too many files at once..working through with them to see if i get consolidate so this might be blueshift catching an error from redshift then not not retrying again

**Comment by pingles** [comment]
Interesting- be good to know if Amazon do enforce an upper bound. If so, we could probably introduce something to paginate through the files in batches- assuming the batches don't grow faster than the rate they're ingested into Redshift :)

Thanks for investigating and keeping us updated!

**Comment by ryanmedlin** [comment]
Just got off chat..

They recommend loading files divisible by the number of nodes to spread it out evenly first of all..

i have an 8 node cluster so he recommends trying 8 or 64 files at a time..

Now i have personally loaded 1000 file at least but sometime redshift will act very weird and abort..

if redshift aborts i am guessing blueshift will not retry that manifest file right and just move on to processing other files that show up?

**Comment by pingles** [comment]
Interesting- could be a nice optimisation to make.

If there's an error whilst Blueshift is importing files it'll leave the files and manifest alone. So, in 5mins (or whatever retry interval you have configured) it'll try importing those same files again plus any new ones that have appeared in the meantime.

I guess the tricky thing is optimising for lots of small files vs. a few massive files (we're probably more the latter but have a few cases of the former). What do you think about adding an option in the manifest file that has an upper batch size- so if you specify 64 it'll take up to 64 files and run an import, then the next 64 etc.?

**Comment by ryanmedlin** [comment]
COMPUPDATE OFF STATUPDATE OFF

setitng those if the table has already been created makes this problem completely go away..  this has been runnign fine i forgot to update this issue i dont think there is any need ot support this case based on that fix..

**Comment by pingles** [comment]
Awesome, good to know. I don't think we'll make those defaults given its
easy to set them yourself in the manifest file, but definitely good to
leave it here in case someone else has a similar problem in the future.

Thanks for keeping us updated!
