### ISSUE TITLE
getting   Serializable isolation violation on table

### ISSUE THREAD

**Issue by ryanmedlin** [uswitch/blueshift#11]
i seem to get these alot lately since our app is running alot of SELECT statement now and its always against the table and the time that blueshift is loading data against the table. 

org.postgresql.util.PSQLException: ERROR: 1023 Detail: Serializable isolation violation on table

i have an open ticket with amazon and see suggestions on locking exclusive the table but blueshift is not doing that i noticed.  does it need to or am i missing something?

**Comment by pingles** [comment]
Hi,

Are you running multiple instances of Blueshift or other systems to load data into the same tables? I wouldn't have thought reads alone would trigger this kind of exception. 

You're correct, we currently don't lock the table- we wrote Blueshift to serialize inserts for us (we don't run any other mutation processes, just Blueshift).

If you're happy to you could try adding an [exclusive lock](http://docs.aws.amazon.com/redshift/latest/dg/r_LOCK.html) around the mutation and see whether that prevents the exceptions (although you would presumably then introduce slow consumers as they'd be held behind locks).

**Comment by ryanmedlin** [comment]
We pulled all the currently running queries during these errors and gave to
amazon....let's see what amazon says before u do anything we def want to
keep running selects in our app during blueshift  loads

**Comment by ryanmedlin** [comment]
here is their response.


im trying to minimize our other update scripts reading from that table directly at this point:    nothing to do on your end and ill review what they are saying as far as loading goes.


Hello Ryan, 

First I would like thank you for your patience into this. So our Redshift engineers have looked into the issue and below are the detailed findings: 

Timeline of events associated to Serializable isolation violations:

1426719 starts 2015-04-15 17:22:21.169426
1426719 READS: project, organization, raw_events_final, stv_identity_highwater - WRITES project
1426721 starts 2015-04-15 17:22:28.233573
1426721 READS: raw_events_final_staging, raw_events_final - WRITES: raw_events_final_staging, raw_events_final
1426721 commits at 2015-04-15 17:23:05.526825
1426748 starts 2015-04-15 17:23:38.117682
1426748 READS raw_events_final, beacon, project
1426719 COMMITS at 2015-04-15 17:23:46.345945

Therefore:

1426719 has to serialize before 1426721 because 1426721 and 1426719 overlap so 1426719 needs to see a pre-1426721 image of 'raw_events_final'.
1426748 has to serialize before 1426719 because 1426748 and 1426719 overlap so 1426748 needs to see a pre-1426719 image of 'project'.
1426721 has to serialize before 1426748 because it committed before 1426748 started so 1426748 has to see its changes to 'raw_events_final'.

This creates an impossible scenario for the following Transactions:

1. 1426748
2. 1426719
3. 1426721
4. 1426748

And the error is then thrown.

There are two transactions which are read-write transactions - 1426719 and 1426721. If it were possible to merge these into a single transaction then the issue would be resolved, but at this time there are two separate transactions which write.

One of the solution is to use lock , other options would be to implement application logic to retry but since you are encountering this very frequently so a process re-design is likely a better idea. You could consider an A-B approach like so: Execute all COPY commands against raw_events_final_staging, after a duration of time point the COPY commands to raw_events_final_staging_2 and lock raw_events_final_staging to ensure copies have finished. Then process the merge from raw_events_final_staging and truncate raw_events_final_staging to prepare it for the next rotation. Repeat the process with raw_events_final_staging_2 and during this time ensure that you are not writing to project by either adding those steps to this same process so they are executed serially or by using LOCK. This is detailed by a Redshift DB Engineer here: https://forums.aws.amazon.com/thread.jspa?threadID=140364&tstart=0

Further details regarding mitigation can be found here:

http://docs.aws.amazon.com/redshift/latest/dg/c_write_readwrite.html
http://docs.aws.amazon.com/redshift/latest/dg/c_serial_isolation.html

I hope that helps. Please feel free to get back to us if you have any further questions.

Best regards,

RAZIUL I.
Amazon Web Services
We value your feedback. Please rate my response using the link below.

**Comment by ryanmedlin** [comment]
raw_events_final is the table we are loading into via blueshift BTW

**Comment by ryanmedlin** [comment]
i guess the only thing i could think of woudl be to allow for some sortof way to inject into the blueshift flow sql to be run as part of a transaction referenced above during that loading process.   since we are sortof updating a few tables based on that raw_events_final table i guess we need to do these sequentially and orchestrate their execution together.

**Comment by pingles** [comment]
Hi Ryan,

Thanks for following up on that- could you give a bit more context about
what you're doing and how you're doing it with Blueshift please? I'm trying
to understand a bit more about what updates happen when/why.

Thanks,
Paul

**Comment by ryanmedlin** [comment]
we were updating some other entity tables dynamically based on a inner subselect on the table getting these exceptions so it got into this cycle.  we are reworking how this autogeneration of entities based on raw data works and decoupling that from this table entirely..  not need to make blueshift more complex to somehow add a way to call additional sql in order.
